[package]
name = "nes"
version = "0.1.0"
authors = ["takuya sato <takuya0219@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
gl = "0.11.0"

[dependencies.sdl2]
version = "0.32.1"
features = ["bundled", "static-link"]
